# My variables
name: "Ruslan's tech blog"
description: Software development related stuff
url: "https://codelearn.me"

plugins:
  - jekyll-sitemap
  - jekyll-feed

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "vendor", "packages"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

exclude:
  - _capsule

feed:
  tags: true
