#!/bin/bash

function up {
    hugo serve
}

function new-post {
    if [ -z "$1" ]; then
        echo "File name must be specified";
        exit 1;
    fi
    hugo new content "content/post/$1"
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
